/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { TouchableOpacity, Platform, StyleSheet, Text, View } from 'react-native';
import RNQuiet from 'react-native-quiet';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--'
  };
  //@"ultrasonic-experimental"
  componentDidMount() {
    RNQuiet
      .start('ultrasonic-experimental');
    RNQuiet.addListener(
      (str) => console.log('got',str),
    );
  }
  render() {
    return (
      <TouchableOpacity
        style={StyleSheet.absoluteFill}
        onPress={() => RNQuiet.send("something")}
      >
        <View style={styles.container}>
          <Text style={styles.welcome}>☆RNQuiet example☆</Text>
          <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
          <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
          <Text style={styles.instructions}>{this.state.message}</Text>
        </View>
      </TouchableOpacity>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
